/**
 * Grafo de Conocimiento — Perfiles de Capacidad de Herramientas Oficiales
 *
 * Este archivo es la FUENTE DE VERDAD del conocimiento del sistema sobre
 * cada herramienta. No contiene lógica de negocio — solo datos.
 *
 * Cada entrada codifica:
 *   - Dominio empresarial y objetivos
 *   - Tipos de entrada y salida (contrato I/O para el grafo)
 *   - Relaciones: qué herramientas preceden, siguen o son alternativas
 *   - Parámetros de ejecución recomendados
 *
 * Este conocimiento es consumido por:
 *   - Tool Intelligence Service (recomendaciones, compatibilidad)
 *   - AI Planner (sprint siguiente)
 *   - Workflow Generator
 */

import type { CapabilityProfile } from '@/lib/tool-intelligence/types'

export const CAPABILITY_PROFILES: Record<string, CapabilityProfile> = {

  // ── AUDIT ────────────────────────────────────────────────────────

  'iso9001-audit': {
    businessDomain: 'quality',
    businessGoals: ['certificación ISO 9001', 'gestión de calidad', 'mejora continua', 'cumplimiento normativo'],
    useCases: [
      'Preparación para auditoría de certificación ISO 9001',
      'Auditoría interna de sistema de gestión de calidad',
      'Evaluación del grado de cumplimiento con la norma',
    ],
    inputTypes: ['structured_data', 'text_brief'],
    outputTypes: ['audit_report', 'compliance_report', 'evaluation_scorecard'],
    expectedOutput: 'Informe de auditoría ISO 9001 con puntuación por cláusula, hallazgos y recomendaciones de mejora',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-sonnet-4-6'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.08,
    qualityLevel: 'professional',
    automationFriendly: true,
    dependencies: [],
    relatedTools: ['corrective-action', 'preventive-action', 'non-conformity', 'quality-inspection'],
    alternativeTools: ['iso27001-audit', 'it-audit'],
  },

  'iso27001-audit': {
    businessDomain: 'it',
    businessGoals: ['certificación ISO 27001', 'seguridad de la información', 'gestión de riesgos IT', 'cumplimiento normativo'],
    useCases: [
      'Auditoría interna del sistema de gestión de seguridad de la información',
      'Preparación para certificación ISO 27001',
      'Evaluación de controles de seguridad',
    ],
    inputTypes: ['structured_data', 'it_asset_list'],
    outputTypes: ['audit_report', 'compliance_report', 'risk_matrix'],
    expectedOutput: 'Informe de cumplimiento ISO 27001 con análisis de controles, gaps identificados y plan de remediación',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-sonnet-4-6'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.10,
    qualityLevel: 'professional',
    automationFriendly: true,
    dependencies: ['hardware-inventory', 'software-inventory', 'access-control'],
    relatedTools: ['it-audit', 'corrective-action', 'access-control'],
    alternativeTools: ['iso9001-audit', 'it-audit'],
  },

  'it-audit': {
    businessDomain: 'it',
    businessGoals: ['auditoría tecnológica', 'gobierno IT', 'evaluación de infraestructura', 'gestión de riesgos IT'],
    useCases: [
      'Revisión periódica de la infraestructura tecnológica',
      'Evaluación de seguridad y disponibilidad de sistemas',
      'Auditoría de cumplimiento de políticas IT',
    ],
    inputTypes: ['it_asset_list', 'structured_data'],
    outputTypes: ['audit_report', 'it_report', 'risk_matrix'],
    expectedOutput: 'Informe de auditoría IT con evaluación de sistemas, riesgos identificados y recomendaciones técnicas',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-sonnet-4-6'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.07,
    qualityLevel: 'professional',
    automationFriendly: true,
    dependencies: ['hardware-inventory', 'software-inventory'],
    relatedTools: ['iso27001-audit', 'access-control', 'backup-verification'],
    alternativeTools: ['iso27001-audit'],
  },

  'seo-audit': {
    businessDomain: 'marketing',
    businessGoals: ['mejorar posicionamiento SEO', 'análisis de presencia digital', 'optimización web', 'incrementar tráfico orgánico'],
    useCases: [
      'Auditoría SEO completa de un sitio web',
      'Diagnóstico previo a rediseño web',
      'Revisión periódica de posicionamiento en buscadores',
    ],
    inputTypes: ['text_brief', 'structured_data'],
    outputTypes: ['audit_report', 'seo_data', 'evaluation_scorecard'],
    expectedOutput: 'Informe de auditoría SEO con puntuación técnica, de contenido y autoridad, lista de problemas prioritarios y recomendaciones',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-sonnet-4-6'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.06,
    qualityLevel: 'professional',
    automationFriendly: true,
    dependencies: [],
    relatedTools: ['seo-checklist', 'editorial-plan', 'campaign-evaluation'],
    alternativeTools: ['social-media-audit'],
  },

  'commercial-audit': {
    businessDomain: 'sales',
    businessGoals: ['evaluación comercial', 'diagnóstico de ventas', 'mejora de rendimiento comercial'],
    useCases: [
      'Evaluación del proceso de ventas y equipo comercial',
      'Diagnóstico previo a reestructuración comercial',
    ],
    inputTypes: ['structured_data', 'crm_record'],
    outputTypes: ['audit_report', 'evaluation_scorecard', 'action_plan'],
    expectedOutput: 'Informe de auditoría comercial con análisis de KPIs, puntos débiles y plan de mejora',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-sonnet-4-6'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.07,
    qualityLevel: 'professional',
    automationFriendly: true,
    dependencies: ['crm-leads', 'sales-pipeline'],
    relatedTools: ['sales-forecast', 'opportunity-tracking'],
    alternativeTools: ['seo-audit'],
  },

  'gdpr-audit': {
    businessDomain: 'legal',
    businessGoals: ['cumplimiento RGPD', 'protección de datos', 'auditoría de privacidad', 'gestión de riesgos legales'],
    useCases: [
      'Evaluación del grado de cumplimiento con el RGPD',
      'Preparación para inspección de autoridad de protección de datos',
      'Diagnóstico inicial de privacidad para nuevas empresas',
    ],
    inputTypes: ['structured_data', 'text_brief'],
    outputTypes: ['audit_report', 'compliance_report', 'risk_matrix'],
    expectedOutput: 'Informe RGPD con análisis por área (tratamientos, derechos, seguridad, transferencias), riesgos y plan de acción',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-sonnet-4-6'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.09,
    qualityLevel: 'professional',
    automationFriendly: true,
    dependencies: [],
    relatedTools: ['corrective-action', 'iso27001-audit'],
    alternativeTools: ['iso27001-audit'],
  },

  // ── HR ───────────────────────────────────────────────────────────

  'employee-onboarding': {
    businessDomain: 'hr',
    businessGoals: ['integración de nuevos empleados', 'reducción de tiempo de adaptación', 'fidelización desde el inicio'],
    useCases: [
      'Proceso estructurado de incorporación de nuevo empleado',
      'Checklist de tareas para primera semana y primer mes',
      'Garantizar que el nuevo empleado tiene accesos y recursos necesarios',
    ],
    inputTypes: ['employee_data', 'text_brief'],
    outputTypes: ['hr_process_result', 'checklist_result', 'action_plan'],
    expectedOutput: 'Plan de onboarding personalizado con tareas por semana, personas responsables y recursos necesarios',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-sonnet-4-6'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.05,
    qualityLevel: 'standard',
    automationFriendly: true,
    dependencies: [],
    relatedTools: ['employee-offboarding', 'job-interview', 'objectives-tracking'],
    alternativeTools: ['performance-review'],
  },

  'employee-offboarding': {
    businessDomain: 'hr',
    businessGoals: ['salida ordenada de empleados', 'transferencia de conocimiento', 'gestión de accesos y recursos'],
    useCases: [
      'Proceso de baja de empleado por renuncia o despido',
      'Gestión de devolución de equipos y revocación de accesos',
      'Entrevista de salida y retención de conocimiento',
    ],
    inputTypes: ['employee_data', 'hr_process_result'],
    outputTypes: ['hr_process_result', 'checklist_result'],
    expectedOutput: 'Plan de offboarding con pasos para transferencia de conocimiento, gestión de activos y cierre administrativo',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-haiku-4-5-20251001'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.03,
    qualityLevel: 'standard',
    automationFriendly: true,
    dependencies: ['employee-onboarding'],
    relatedTools: ['access-control', 'asset-inventory'],
    alternativeTools: [],
  },

  'annual-review': {
    businessDomain: 'hr',
    businessGoals: ['evaluación anual de desempeño', 'identificación de talento', 'planificación de carrera'],
    useCases: [
      'Revisión anual estructurada de desempeño de empleados',
      'Identificación de áreas de mejora y fortalezas',
      'Base para decisiones de promoción o aumento salarial',
    ],
    inputTypes: ['employee_data', 'evaluation_scorecard'],
    outputTypes: ['evaluation_scorecard', 'hr_process_result', 'action_plan'],
    expectedOutput: 'Informe de revisión anual con puntuaciones por competencia, análisis de logros, áreas de mejora y plan de desarrollo',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-sonnet-4-6'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.07,
    qualityLevel: 'professional',
    automationFriendly: true,
    dependencies: ['objectives-tracking', 'performance-review'],
    relatedTools: ['objectives-tracking', 'performance-review', 'job-interview'],
    alternativeTools: ['performance-review'],
  },

  'objectives-tracking': {
    businessDomain: 'hr',
    businessGoals: ['gestión por objetivos', 'seguimiento de OKRs', 'alineación estratégica', 'medición de desempeño'],
    useCases: [
      'Definición y seguimiento de objetivos OKR o similares',
      'Revisión trimestral de progreso de objetivos',
      'Alineación de objetivos individuales con estrategia corporativa',
    ],
    inputTypes: ['employee_data', 'strategy_document'],
    outputTypes: ['evaluation_scorecard', 'hr_process_result'],
    expectedOutput: 'Registro de objetivos con estado de avance, puntuación de cumplimiento y recomendaciones',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-haiku-4-5-20251001'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.04,
    qualityLevel: 'standard',
    automationFriendly: true,
    dependencies: ['strategic-plan'],
    relatedTools: ['annual-review', 'performance-review'],
    alternativeTools: ['performance-review'],
  },

  'job-interview': {
    businessDomain: 'hr',
    businessGoals: ['selección de personal', 'evaluación de candidatos', 'estructuración de entrevistas'],
    useCases: [
      'Proceso estructurado de entrevista de selección',
      'Evaluación comparativa de candidatos',
      'Documentación de entrevistas para decisión de contratación',
    ],
    inputTypes: ['employee_data', 'text_brief'],
    outputTypes: ['evaluation_scorecard', 'hr_process_result'],
    expectedOutput: 'Informe de evaluación del candidato con puntuación por competencia, conclusión y recomendación de contratación',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-sonnet-4-6'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.06,
    qualityLevel: 'standard',
    automationFriendly: true,
    dependencies: [],
    relatedTools: ['employee-onboarding', 'performance-review'],
    alternativeTools: [],
  },

  'performance-review': {
    businessDomain: 'hr',
    businessGoals: ['evaluación de desempeño', 'feedback estructurado', 'desarrollo profesional'],
    useCases: [
      'Evaluación periódica de desempeño (trimestral o semestral)',
      'Feedback 360º estructurado',
      'Identificación de necesidades de formación',
    ],
    inputTypes: ['employee_data', 'evaluation_scorecard'],
    outputTypes: ['evaluation_scorecard', 'hr_process_result', 'action_plan'],
    expectedOutput: 'Evaluación de desempeño con análisis de competencias, logros del período, áreas de mejora y plan de acción',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-sonnet-4-6'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.06,
    qualityLevel: 'standard',
    automationFriendly: true,
    dependencies: ['objectives-tracking'],
    relatedTools: ['annual-review', 'objectives-tracking'],
    alternativeTools: ['annual-review'],
  },

  // ── QUALITY ──────────────────────────────────────────────────────

  'non-conformity': {
    businessDomain: 'quality',
    businessGoals: ['gestión de no conformidades', 'control de calidad', 'trazabilidad de incidencias'],
    useCases: [
      'Registro y análisis de no conformidades detectadas',
      'Trazabilidad de defectos desde detección hasta cierre',
      'Estadísticas de calidad por período',
    ],
    inputTypes: ['structured_data', 'audit_report', 'quality_record'],
    outputTypes: ['quality_record', 'action_plan'],
    expectedOutput: 'Registro de no conformidad con análisis de causa raíz, impacto, acciones correctivas propuestas y seguimiento',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-haiku-4-5-20251001'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.03,
    qualityLevel: 'standard',
    automationFriendly: true,
    dependencies: ['quality-inspection', 'iso9001-audit'],
    relatedTools: ['corrective-action', 'preventive-action'],
    alternativeTools: ['corrective-action'],
  },

  'corrective-action': {
    businessDomain: 'quality',
    businessGoals: ['resolución de no conformidades', 'mejora continua', 'eliminación de causas raíz'],
    useCases: [
      'Definición de acciones correctivas tras auditoría o no conformidad',
      'Seguimiento hasta el cierre de la acción correctiva',
      'Verificación de eficacia de la acción implementada',
    ],
    inputTypes: ['audit_report', 'quality_record', 'evaluation_scorecard'],
    outputTypes: ['action_plan', 'quality_record'],
    expectedOutput: 'Plan de acción correctiva con causa raíz identificada, acciones concretas, responsables, plazos y criterios de verificación',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-sonnet-4-6'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.05,
    qualityLevel: 'standard',
    automationFriendly: true,
    dependencies: ['non-conformity', 'iso9001-audit'],
    relatedTools: ['preventive-action', 'non-conformity'],
    alternativeTools: ['preventive-action'],
  },

  'preventive-action': {
    businessDomain: 'quality',
    businessGoals: ['prevención de no conformidades', 'gestión proactiva de calidad', 'mejora continua preventiva'],
    useCases: [
      'Identificación y gestión de riesgos de calidad antes de que ocurran',
      'Implementación de mejoras preventivas',
    ],
    inputTypes: ['risk_matrix', 'audit_report', 'quality_record'],
    outputTypes: ['action_plan', 'quality_record'],
    expectedOutput: 'Plan de acción preventiva con riesgo identificado, acciones de mitigación y seguimiento',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-haiku-4-5-20251001'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.03,
    qualityLevel: 'standard',
    automationFriendly: true,
    dependencies: ['iso9001-audit', 'quality-inspection'],
    relatedTools: ['corrective-action', 'non-conformity'],
    alternativeTools: ['corrective-action'],
  },

  'production-checklist': {
    businessDomain: 'quality',
    businessGoals: ['control de producción', 'estandarización de procesos', 'trazabilidad de lotes'],
    useCases: [
      'Verificación de calidad en línea de producción',
      'Control de lote antes de expedición',
    ],
    inputTypes: ['structured_data'],
    outputTypes: ['checklist_result', 'quality_record'],
    expectedOutput: 'Resultado del checklist de producción con ítems verificados, no conformidades detectadas y firma de responsable',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-haiku-4-5-20251001'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.02,
    qualityLevel: 'standard',
    automationFriendly: true,
    dependencies: [],
    relatedTools: ['quality-inspection', 'non-conformity'],
    alternativeTools: ['quality-inspection'],
  },

  'quality-inspection': {
    businessDomain: 'quality',
    businessGoals: ['inspección de calidad', 'control de recepción', 'verificación de especificaciones'],
    useCases: [
      'Inspección de recepción de materias primas o productos',
      'Evaluación de calidad de lote de producción',
    ],
    inputTypes: ['structured_data', 'supplier_data'],
    outputTypes: ['evaluation_scorecard', 'quality_record', 'checklist_result'],
    expectedOutput: 'Resultado de inspección con puntuación por criterio, veredicto de aceptación/rechazo y registro fotográfico estructurado',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-haiku-4-5-20251001'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.03,
    qualityLevel: 'standard',
    automationFriendly: true,
    dependencies: [],
    relatedTools: ['non-conformity', 'supplier-evaluation', 'production-checklist'],
    alternativeTools: ['production-checklist'],
  },

  // ── PURCHASING / PROCUREMENT ─────────────────────────────────────

  'supplier-evaluation': {
    businessDomain: 'procurement',
    businessGoals: ['evaluación de proveedores', 'homologación', 'gestión de riesgos de suministro', 'reducción de costes'],
    useCases: [
      'Evaluación periódica de rendimiento de proveedor',
      'Comparativa de proveedores para selección',
      'Auditoría de calidad de suministro',
    ],
    inputTypes: ['supplier_data', 'structured_data'],
    outputTypes: ['evaluation_scorecard', 'supplier_data', 'action_plan'],
    expectedOutput: 'Scorecard de evaluación del proveedor con puntuación por criterio (calidad, precio, plazo, servicio) y recomendación de continuidad',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-sonnet-4-6'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.06,
    qualityLevel: 'professional',
    automationFriendly: true,
    dependencies: [],
    relatedTools: ['supplier-homologation', 'offer-comparison', 'quality-inspection'],
    alternativeTools: ['supplier-homologation'],
  },

  'supplier-homologation': {
    businessDomain: 'procurement',
    businessGoals: ['homologación de nuevos proveedores', 'gestión de base de proveedores', 'cumplimiento normativo de compras'],
    useCases: [
      'Proceso de alta y homologación de nuevo proveedor',
      'Renovación de homologación de proveedor existente',
    ],
    inputTypes: ['supplier_data', 'text_brief'],
    outputTypes: ['compliance_report', 'supplier_data'],
    expectedOutput: 'Informe de homologación con evaluación de criterios obligatorios, documentación recibida y veredicto de aprobación',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-haiku-4-5-20251001'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.04,
    qualityLevel: 'standard',
    automationFriendly: true,
    dependencies: [],
    relatedTools: ['supplier-evaluation', 'offer-comparison'],
    alternativeTools: ['supplier-evaluation'],
  },

  'goods-reception': {
    businessDomain: 'procurement',
    businessGoals: ['control de recepción de mercancías', 'trazabilidad de entradas', 'gestión de no conformidades en recepción'],
    useCases: [
      'Registro de entrada de mercancías con verificación de albarán',
      'Control de calidad en recepción',
    ],
    inputTypes: ['supplier_data', 'structured_data'],
    outputTypes: ['quality_record', 'checklist_result'],
    expectedOutput: 'Registro de recepción con verificación de cantidad, calidad y documentación, incidencias detectadas',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-haiku-4-5-20251001'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.02,
    qualityLevel: 'standard',
    automationFriendly: true,
    dependencies: ['supplier-evaluation'],
    relatedTools: ['quality-inspection', 'non-conformity'],
    alternativeTools: [],
  },

  'offer-comparison': {
    businessDomain: 'procurement',
    businessGoals: ['comparativa de ofertas', 'optimización de costes', 'toma de decisiones de compra'],
    useCases: [
      'Comparación estructurada de ofertas de múltiples proveedores',
      'Análisis coste-beneficio para decisión de compra',
    ],
    inputTypes: ['supplier_data', 'financial_data'],
    outputTypes: ['evaluation_scorecard', 'financial_data', 'action_plan'],
    expectedOutput: 'Análisis comparativo de ofertas con puntuación ponderada, tabla comparativa y recomendación de adjudicación',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-sonnet-4-6'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.05,
    qualityLevel: 'professional',
    automationFriendly: true,
    dependencies: ['supplier-evaluation', 'supplier-homologation'],
    relatedTools: ['supplier-evaluation', 'expense-control'],
    alternativeTools: [],
  },

  // ── SALES / CRM ──────────────────────────────────────────────────

  'crm-leads': {
    businessDomain: 'sales',
    businessGoals: ['gestión de leads', 'seguimiento de pipeline', 'conversión de oportunidades'],
    useCases: [
      'Registro y seguimiento de leads comerciales',
      'Cualificación de oportunidades',
      'Gestión de contactos y actividad comercial',
    ],
    inputTypes: ['text_brief', 'structured_data'],
    outputTypes: ['crm_record', 'structured_data'],
    expectedOutput: 'Registro de lead con datos de contacto, estado de cualificación, próximas acciones y probabilidad de cierre',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-haiku-4-5-20251001'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.02,
    qualityLevel: 'standard',
    automationFriendly: true,
    dependencies: [],
    relatedTools: ['opportunity-tracking', 'commercial-visit', 'sales-pipeline'],
    alternativeTools: ['opportunity-tracking'],
  },

  'opportunity-tracking': {
    businessDomain: 'sales',
    businessGoals: ['seguimiento de oportunidades', 'gestión de pipeline', 'previsión de ventas'],
    useCases: [
      'Seguimiento del estado de oportunidades comerciales en curso',
      'Actualización del pipeline de ventas',
    ],
    inputTypes: ['crm_record', 'structured_data'],
    outputTypes: ['crm_record', 'evaluation_scorecard'],
    expectedOutput: 'Estado actualizado de oportunidad con etapa del pipeline, probabilidad, fecha estimada de cierre y próximas acciones',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-haiku-4-5-20251001'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.02,
    qualityLevel: 'standard',
    automationFriendly: true,
    dependencies: ['crm-leads', 'commercial-visit'],
    relatedTools: ['sales-pipeline', 'sales-forecast', 'crm-leads'],
    alternativeTools: ['sales-pipeline'],
  },

  'commercial-visit': {
    businessDomain: 'sales',
    businessGoals: ['registro de visitas comerciales', 'seguimiento de clientes', 'documentación de reuniones'],
    useCases: [
      'Informe de visita comercial a cliente',
      'Documentación de reunión de seguimiento',
    ],
    inputTypes: ['crm_record', 'text_brief'],
    outputTypes: ['crm_record', 'action_plan'],
    expectedOutput: 'Informe de visita con resumen de reunión, compromisos adquiridos, próximos pasos y actualización del CRM',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-haiku-4-5-20251001'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.03,
    qualityLevel: 'standard',
    automationFriendly: true,
    dependencies: ['crm-leads'],
    relatedTools: ['opportunity-tracking', 'discovery-session'],
    alternativeTools: ['discovery-session'],
  },

  'discovery-session': {
    businessDomain: 'sales',
    businessGoals: ['cualificación de prospectos', 'identificación de necesidades', 'propuesta de valor'],
    useCases: [
      'Sesión estructurada de discovery con prospecto',
      'Identificación de pain points y oportunidades de negocio',
    ],
    inputTypes: ['text_brief', 'crm_record'],
    outputTypes: ['crm_record', 'analysis_result'],
    expectedOutput: 'Resumen de sesión de discovery con necesidades identificadas, fit con solución, próximos pasos y nivel de cualificación',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-sonnet-4-6'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.05,
    qualityLevel: 'standard',
    automationFriendly: true,
    dependencies: [],
    relatedTools: ['commercial-visit', 'opportunity-tracking'],
    alternativeTools: ['commercial-visit'],
  },

  'sales-pipeline': {
    businessDomain: 'sales',
    businessGoals: ['gestión de pipeline', 'visibilidad de ventas', 'previsión de ingresos'],
    useCases: [
      'Visión global del pipeline de ventas del equipo',
      'Análisis de conversión por etapa del pipeline',
    ],
    inputTypes: ['crm_record', 'structured_data'],
    outputTypes: ['evaluation_scorecard', 'structured_data', 'analysis_result'],
    expectedOutput: 'Resumen del pipeline con oportunidades por etapa, valor total, tasa de conversión y alertas de riesgo',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-sonnet-4-6'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.05,
    qualityLevel: 'standard',
    automationFriendly: true,
    dependencies: ['crm-leads', 'opportunity-tracking'],
    relatedTools: ['sales-forecast', 'commercial-audit'],
    alternativeTools: ['sales-forecast'],
  },

  'sales-forecast': {
    businessDomain: 'sales',
    businessGoals: ['previsión de ventas', 'planificación financiera', 'objetivos comerciales'],
    useCases: [
      'Previsión de ventas mensual o trimestral',
      'Análisis de desviación vs objetivo',
    ],
    inputTypes: ['crm_record', 'financial_data', 'analysis_result'],
    outputTypes: ['financial_data', 'analysis_result', 'action_plan'],
    expectedOutput: 'Previsión de ventas con proyección por período, análisis de pipeline ponderado, riesgos y oportunidades',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-sonnet-4-6'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.06,
    qualityLevel: 'professional',
    automationFriendly: true,
    dependencies: ['sales-pipeline', 'opportunity-tracking'],
    relatedTools: ['sales-pipeline', 'commercial-audit'],
    alternativeTools: [],
  },

  // ── MARKETING ────────────────────────────────────────────────────

  'editorial-plan': {
    businessDomain: 'marketing',
    businessGoals: ['planificación de contenidos', 'estrategia editorial', 'calendarios de publicación'],
    useCases: [
      'Plan editorial mensual o trimestral para blog/redes',
      'Calendarización de contenidos por canal',
    ],
    inputTypes: ['text_brief', 'analysis_result', 'market_data'],
    outputTypes: ['campaign_data', 'action_plan', 'strategy_document'],
    expectedOutput: 'Plan editorial con calendario de publicaciones, temas, canales, responsables y KPIs de cada contenido',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-sonnet-4-6'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.06,
    qualityLevel: 'standard',
    automationFriendly: true,
    dependencies: ['campaign-brief'],
    relatedTools: ['campaign-brief', 'seo-checklist', 'campaign-evaluation'],
    alternativeTools: ['campaign-brief'],
  },

  'campaign-brief': {
    businessDomain: 'marketing',
    businessGoals: ['briefing de campañas', 'definición de estrategia de campaña', 'alineación de equipo creativo'],
    useCases: [
      'Briefing inicial para campaña de marketing',
      'Definición de objetivos, público y mensajes clave',
    ],
    inputTypes: ['text_brief', 'market_data', 'analysis_result'],
    outputTypes: ['campaign_data', 'strategy_document'],
    expectedOutput: 'Brief de campaña completo con objetivos, segmento objetivo, propuesta de valor, canales, presupuesto y KPIs',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-sonnet-4-6'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.06,
    qualityLevel: 'professional',
    automationFriendly: true,
    dependencies: ['swot-analysis', 'company-diagnosis'],
    relatedTools: ['editorial-plan', 'campaign-evaluation', 'seo-checklist'],
    alternativeTools: ['editorial-plan'],
  },

  'social-media-audit': {
    businessDomain: 'marketing',
    businessGoals: ['auditoría de redes sociales', 'análisis de presencia digital', 'optimización de social media'],
    useCases: [
      'Evaluación de presencia y rendimiento en redes sociales',
      'Diagnóstico previo a nueva estrategia de social media',
    ],
    inputTypes: ['text_brief', 'campaign_data'],
    outputTypes: ['audit_report', 'evaluation_scorecard', 'action_plan'],
    expectedOutput: 'Auditoría de redes con análisis de engagement, benchmark vs competencia, fortalezas y plan de mejora',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-sonnet-4-6'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.06,
    qualityLevel: 'standard',
    automationFriendly: true,
    dependencies: [],
    relatedTools: ['seo-audit', 'campaign-evaluation', 'editorial-plan'],
    alternativeTools: ['seo-audit'],
  },

  'seo-checklist': {
    businessDomain: 'marketing',
    businessGoals: ['optimización SEO on-page', 'mejora de contenidos', 'checklist técnico SEO'],
    useCases: [
      'Verificación de requisitos SEO antes de publicar contenido',
      'Revisión técnica SEO de página web',
    ],
    inputTypes: ['seo_data', 'audit_report', 'text_brief'],
    outputTypes: ['checklist_result', 'action_plan'],
    expectedOutput: 'Checklist SEO completado con ítems verificados, errores detectados y priorización de correcciones',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-haiku-4-5-20251001'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.02,
    qualityLevel: 'standard',
    automationFriendly: true,
    dependencies: ['seo-audit'],
    relatedTools: ['seo-audit', 'editorial-plan'],
    alternativeTools: [],
  },

  'campaign-evaluation': {
    businessDomain: 'marketing',
    businessGoals: ['evaluación de campañas', 'análisis de ROI', 'mejora de futuras campañas'],
    useCases: [
      'Evaluación de resultados de campaña de marketing',
      'Análisis de ROI y KPIs de campaña',
    ],
    inputTypes: ['campaign_data', 'financial_data', 'analysis_result'],
    outputTypes: ['evaluation_scorecard', 'analysis_result', 'action_plan'],
    expectedOutput: 'Informe de evaluación de campaña con KPIs conseguidos vs objetivo, análisis de ROI y recomendaciones',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-sonnet-4-6'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.06,
    qualityLevel: 'professional',
    automationFriendly: true,
    dependencies: ['campaign-brief'],
    relatedTools: ['campaign-brief', 'editorial-plan', 'social-media-audit'],
    alternativeTools: [],
  },

  // ── CONSULTING / STRATEGY ─────────────────────────────────────────

  'swot-analysis': {
    businessDomain: 'strategy',
    businessGoals: ['análisis estratégico', 'diagnóstico empresarial', 'identificación de oportunidades y amenazas', 'planificación estratégica'],
    useCases: [
      'Análisis DAFO/SWOT completo de empresa o unidad de negocio',
      'Diagnóstico previo a proceso de planificación estratégica',
      'Revisión anual de posicionamiento estratégico',
    ],
    inputTypes: ['text_brief', 'structured_data'],
    outputTypes: ['analysis_result', 'strategy_document'],
    expectedOutput: 'Análisis DAFO completo con factores clasificados por cuadrante, puntuación de impacto y líneas estratégicas derivadas',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-sonnet-4-6'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.07,
    qualityLevel: 'professional',
    automationFriendly: true,
    dependencies: [],
    relatedTools: ['strategic-plan', 'company-diagnosis', 'digital-maturity'],
    alternativeTools: ['company-diagnosis'],
  },

  'digital-maturity': {
    businessDomain: 'strategy',
    businessGoals: ['evaluación de madurez digital', 'transformación digital', 'diagnóstico tecnológico'],
    useCases: [
      'Diagnóstico del nivel de madurez digital de la empresa',
      'Identificación de brechas digitales y hoja de ruta',
    ],
    inputTypes: ['text_brief', 'structured_data', 'it_asset_list'],
    outputTypes: ['evaluation_scorecard', 'analysis_result', 'strategy_document'],
    expectedOutput: 'Scorecard de madurez digital por dimensión (tecnología, procesos, personas, datos, cultura) con hoja de ruta de mejora',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-sonnet-4-6'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.08,
    qualityLevel: 'professional',
    automationFriendly: true,
    dependencies: [],
    relatedTools: ['swot-analysis', 'strategic-plan', 'it-audit'],
    alternativeTools: ['swot-analysis', 'company-diagnosis'],
  },

  'company-diagnosis': {
    businessDomain: 'strategy',
    businessGoals: ['diagnóstico empresarial completo', 'análisis organizacional', 'consultoría de negocio'],
    useCases: [
      'Diagnóstico integral de empresa para consultoría',
      'Evaluación previa a procesos de cambio organizacional',
      'Análisis de situación actual para plan estratégico',
    ],
    inputTypes: ['text_brief', 'structured_data', 'analysis_result'],
    outputTypes: ['analysis_result', 'strategy_document', 'evaluation_scorecard'],
    expectedOutput: 'Diagnóstico empresarial completo con análisis de áreas funcionales, puntuación de madurez, fortalezas críticas y plan de acción prioritario',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-sonnet-4-6'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.10,
    qualityLevel: 'professional',
    automationFriendly: true,
    dependencies: [],
    relatedTools: ['swot-analysis', 'strategic-plan', 'process-map'],
    alternativeTools: ['swot-analysis'],
  },

  'strategic-plan': {
    businessDomain: 'strategy',
    businessGoals: ['planificación estratégica', 'definición de objetivos a largo plazo', 'hoja de ruta empresarial'],
    useCases: [
      'Elaboración del plan estratégico anual o trianual',
      'Definición de misión, visión y objetivos estratégicos',
      'Alineación de iniciativas con estrategia corporativa',
    ],
    inputTypes: ['analysis_result', 'strategy_document', 'evaluation_scorecard'],
    outputTypes: ['strategy_document', 'action_plan'],
    expectedOutput: 'Plan estratégico con misión, visión, valores, líneas estratégicas, objetivos SMART, iniciativas y cuadro de mando',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-opus-4-8'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.15,
    qualityLevel: 'professional',
    automationFriendly: false,
    dependencies: ['swot-analysis', 'company-diagnosis'],
    relatedTools: ['swot-analysis', 'company-diagnosis', 'objectives-tracking'],
    alternativeTools: [],
  },

  'process-map': {
    businessDomain: 'operations',
    businessGoals: ['mapeo de procesos', 'documentación de procedimientos', 'optimización operacional'],
    useCases: [
      'Documentación de procesos clave de la empresa',
      'Identificación de ineficiencias en procesos',
      'Preparación de manual de procedimientos',
    ],
    inputTypes: ['text_brief', 'structured_data'],
    outputTypes: ['process_map', 'strategy_document', 'action_plan'],
    expectedOutput: 'Mapa de proceso con flujo, responsables por etapa, inputs/outputs, puntos de control y métricas de eficiencia',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-sonnet-4-6'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.07,
    qualityLevel: 'professional',
    automationFriendly: true,
    dependencies: ['company-diagnosis'],
    relatedTools: ['strategic-plan', 'corrective-action'],
    alternativeTools: [],
  },

  // ── ADMINISTRATION ────────────────────────────────────────────────

  'asset-inventory': {
    businessDomain: 'admin',
    businessGoals: ['control de activos', 'inventario empresarial', 'gestión patrimonial'],
    useCases: [
      'Inventario completo de activos de la empresa',
      'Control de asignación de activos a empleados',
    ],
    inputTypes: ['structured_data'],
    outputTypes: ['structured_data', 'action_plan'],
    expectedOutput: 'Inventario de activos con clasificación, estado, responsable asignado y valoración actualizada',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-haiku-4-5-20251001'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.02,
    qualityLevel: 'standard',
    automationFriendly: true,
    dependencies: [],
    relatedTools: ['license-control', 'expense-control'],
    alternativeTools: ['license-control'],
  },

  'contract-review': {
    businessDomain: 'legal',
    businessGoals: ['revisión de contratos', 'gestión documental legal', 'control de obligaciones contractuales'],
    useCases: [
      'Revisión y análisis de contratos con proveedores o clientes',
      'Identificación de cláusulas de riesgo',
    ],
    inputTypes: ['text_brief', 'structured_data'],
    outputTypes: ['compliance_report', 'risk_matrix', 'action_plan'],
    expectedOutput: 'Análisis de contrato con cláusulas clave, riesgos identificados, obligaciones y recomendaciones legales',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-sonnet-4-6'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.09,
    qualityLevel: 'professional',
    automationFriendly: false,
    dependencies: [],
    relatedTools: ['supplier-homologation', 'gdpr-audit'],
    alternativeTools: [],
  },

  'expense-control': {
    businessDomain: 'finance',
    businessGoals: ['control de gastos', 'gestión presupuestaria', 'optimización de costes'],
    useCases: [
      'Registro y control de gastos empresariales',
      'Análisis de desviación presupuestaria',
    ],
    inputTypes: ['financial_data', 'structured_data'],
    outputTypes: ['financial_data', 'evaluation_scorecard', 'action_plan'],
    expectedOutput: 'Informe de gastos con categorización, análisis de desviación vs presupuesto y recomendaciones de ahorro',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-haiku-4-5-20251001'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.03,
    qualityLevel: 'standard',
    automationFriendly: true,
    dependencies: [],
    relatedTools: ['offer-comparison', 'sales-forecast'],
    alternativeTools: [],
  },

  'license-control': {
    businessDomain: 'it',
    businessGoals: ['control de licencias software', 'cumplimiento de licencias', 'optimización de costes IT'],
    useCases: [
      'Inventario y control de licencias de software',
      'Verificación de cumplimiento de términos de licencia',
    ],
    inputTypes: ['it_asset_list', 'structured_data'],
    outputTypes: ['compliance_report', 'structured_data'],
    expectedOutput: 'Registro de licencias con estado de cumplimiento, fecha de renovación, coste y alertas de expiración',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-haiku-4-5-20251001'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.02,
    qualityLevel: 'standard',
    automationFriendly: true,
    dependencies: ['software-inventory'],
    relatedTools: ['software-inventory', 'asset-inventory', 'iso27001-audit'],
    alternativeTools: ['software-inventory'],
  },

  // ── IT ────────────────────────────────────────────────────────────

  'access-control': {
    businessDomain: 'it',
    businessGoals: ['control de accesos', 'seguridad IT', 'principio de mínimo privilegio'],
    useCases: [
      'Auditoría de permisos y accesos de usuarios',
      'Gestión de altas y bajas de accesos',
    ],
    inputTypes: ['employee_data', 'it_asset_list'],
    outputTypes: ['compliance_report', 'checklist_result', 'it_report'],
    expectedOutput: 'Informe de accesos con usuarios, permisos asignados, accesos innecesarios identificados y recomendaciones',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-haiku-4-5-20251001'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.03,
    qualityLevel: 'standard',
    automationFriendly: true,
    dependencies: [],
    relatedTools: ['iso27001-audit', 'it-audit', 'hardware-inventory'],
    alternativeTools: [],
  },

  'backup-verification': {
    businessDomain: 'it',
    businessGoals: ['verificación de copias de seguridad', 'continuidad de negocio', 'recuperación ante desastres'],
    useCases: [
      'Verificación periódica de copias de seguridad',
      'Test de restauración de backup',
    ],
    inputTypes: ['it_asset_list', 'structured_data'],
    outputTypes: ['checklist_result', 'it_report'],
    expectedOutput: 'Informe de verificación de backups con estado por sistema, última copia exitosa, prueba de restauración y alertas',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-haiku-4-5-20251001'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.02,
    qualityLevel: 'standard',
    automationFriendly: true,
    dependencies: [],
    relatedTools: ['it-audit', 'iso27001-audit', 'deployment-checklist'],
    alternativeTools: [],
  },

  'deployment-checklist': {
    businessDomain: 'it',
    businessGoals: ['control de despliegues', 'gestión de cambios IT', 'reducción de incidencias en producción'],
    useCases: [
      'Checklist previo a despliegue en producción',
      'Proceso de release controlado',
    ],
    inputTypes: ['structured_data', 'text_brief'],
    outputTypes: ['checklist_result', 'it_report'],
    expectedOutput: 'Checklist de despliegue con ítems verificados, go/no-go decision y registro de aprobaciones',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-haiku-4-5-20251001'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.02,
    qualityLevel: 'standard',
    automationFriendly: true,
    dependencies: ['backup-verification'],
    relatedTools: ['it-incidents', 'it-audit'],
    alternativeTools: [],
  },

  'hardware-inventory': {
    businessDomain: 'it',
    businessGoals: ['inventario de hardware', 'control de activos IT', 'gestión del ciclo de vida de equipos'],
    useCases: [
      'Inventario completo de equipos físicos de la empresa',
      'Control de asignación de equipos a empleados',
    ],
    inputTypes: ['structured_data'],
    outputTypes: ['it_asset_list', 'structured_data'],
    expectedOutput: 'Inventario de hardware con especificaciones, estado, responsable y fecha de renovación estimada',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-haiku-4-5-20251001'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.02,
    qualityLevel: 'standard',
    automationFriendly: true,
    dependencies: [],
    relatedTools: ['software-inventory', 'access-control', 'iso27001-audit'],
    alternativeTools: ['asset-inventory'],
  },

  'it-incidents': {
    businessDomain: 'it',
    businessGoals: ['gestión de incidentes IT', 'resolución de problemas técnicos', 'trazabilidad de incidencias'],
    useCases: [
      'Registro y gestión de incidentes de sistemas',
      'Análisis de causa raíz de incidentes recurrentes',
    ],
    inputTypes: ['structured_data', 'it_report'],
    outputTypes: ['quality_record', 'action_plan', 'it_report'],
    expectedOutput: 'Registro de incidente con síntomas, causa raíz, acciones de resolución, tiempo de restauración y lecciones aprendidas',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-haiku-4-5-20251001'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.03,
    qualityLevel: 'standard',
    automationFriendly: true,
    dependencies: [],
    relatedTools: ['deployment-checklist', 'corrective-action', 'it-audit'],
    alternativeTools: ['non-conformity'],
  },

  'software-inventory': {
    businessDomain: 'it',
    businessGoals: ['inventario de software', 'control de licencias', 'gestión de aplicaciones'],
    useCases: [
      'Inventario completo de aplicaciones y software instalado',
      'Control de versiones y actualizaciones pendientes',
    ],
    inputTypes: ['structured_data'],
    outputTypes: ['it_asset_list', 'structured_data'],
    expectedOutput: 'Inventario de software con aplicaciones, versiones, licencias, estado de actualización y coste anual',
    requiredVariables: [],
    optionalVariables: [],
    recommendedModels: ['claude-haiku-4-5-20251001'],
    supportedProviders: ['anthropic'],
    executionCostEUR: 0.02,
    qualityLevel: 'standard',
    automationFriendly: true,
    dependencies: [],
    relatedTools: ['hardware-inventory', 'license-control', 'iso27001-audit'],
    alternativeTools: ['hardware-inventory'],
  },
}
